configs:

  - chainlit_config:
      - host: localhost
      - port: 8000

  - qdrant_config:
      - collection_name: papers
      
  - embedding_config: # If you want to change model, also change the other settings accordingly
      - model: nomic-embed-text:137m-v1.5-fp16 # ollama model id
      - tokenizer: nomic-ai/nomic-embed-text-v1.5 # huggingface model id
      - max_seq_length: 8192
      - output_length: 768
      - image_model: nomic-ai/nomic-embed-vision-v1.5 # huggingface model id
      - use_same_output_length: True # use the same output length for text and image embeddings
      - img_output_length: null # set if use_same_output_length is False

  - chunking_config:
      - use_emb_model_max_seq_length: False
      - chunk_size: 500 # set if use_emb_model_max_seq_length is False
      - chunk_size_penalty: 20 # decreases max chunk size by amount, used to append section titles to chunks
      - chunk_overlap_percent: 0.2